Repository milieuinfo/webcomponent-vl-ui-progress-bar, pull requests merged in 2020-07, with the labels that each got.

#21 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#22 Update dependencies
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#23 Introductie disabled progress-bar-step cursor stijl
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-progress-bar.js
  dist/vl-progress-bar.min.js
  dist/vl-progress-bar.src.js
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-progress-bar.js
  test/unit/vl-progress-bar.test.html
Labels: enhancement
