Repository milieuinfo/webcomponent-vl-ui-progress-bar, pull requests merged in 2020-04, with the labels that each got.

#4 Introductie DOM en buttons getters In kader van vl-ui-wizard
  dist/index.js
  dist/vl-progress-bar-all.js
  dist/vl-progress-bar-all.min.js
  dist/vl-progress-bar-all.src.js
  dist/vl-progress-bar-item.min.js
  dist/vl-progress-bar-step.js
  dist/vl-progress-bar-step.min.js
  dist/vl-progress-bar-step.src.js
  dist/vl-progress-bar.js
  dist/vl-progress-bar.min.js
  dist/vl-progress-bar.src.js
  src/vl-progress-bar-step.js
  src/vl-progress-bar.js
  test/e2e/components/vl-progress-bar-step.js
  test/unit/vl-progress-bar-step.test.html
  test/unit/vl-progress-bar.test.html
Labels: enhancement

#2 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#6 Ontbrekende dependencies van @govflanders toegevoegd
  package-lock.json
  package.json
Labels: bug

#8 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#9 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
